In [1]:
import pandas as pd

pd.set_option('display.max_rows', 120)
pd.set_option('display.max_colwidth', 100)

df = pd.read_json('data/italy.json')
print(df.shape)
df.columns

(103, 16)

Index(['id', 'name', 'type', 'city', 'region', 'neighborhood', 'description',
       'latitude', 'longitude', 'hours', 'duration_minutes', 'price_range',
       'rating', 'tags', 'seasonal_notes', 'booking_required'],
      dtype='str')

In [2]:
df.head()

,id,name,type,city,region,neighborhood,description,latitude,longitude,hours,duration_minutes,price_range,rating,tags,seasonal_notes,booking_required
0,place_001,Colosseum,historic_site,Rome,Lazio,Celio,The most iconic structure in Rome — go early morning or book the evening experience to avoid the...,41.8902,12.4922,9:00-19:00,120.0,€€,4.8,"[iconic, historic, tourist-heavy, cultural]",Summer queues can be brutal — pre-book online always.,1.0
1,place_002,Trastevere Neighborhood,neighborhood,Rome,Lazio,Trastevere,"Rome's most atmospheric quarter — cobblestones, ivy-covered walls, and the best evening energy i...",41.8893,12.4706,NaN,180.0,€,4.7,"[romantic, evening, local-favorite, scenic, food]",NaN,0.0
2,place_003,Da Enzo al 29,restaurant,Rome,Lazio,Trastevere,Skip the tourist menus on the main drag — this place two streets back does cacio e pepe and coda...,41.8875,12.4720,"Mon-Sat 12:30-14:30, 19:30-22:30",90.0,€€,4.6,"[food, local-favorite, hidden-gem, cultural]",NaN,1.0
3,place_004,Roman Forum,historic_site,Rome,Lazio,Celio,"Combine with the Colosseum on the same ticket — the Forum is where the city actually happened, a...",41.8925,12.4853,9:00-19:00,90.0,€€,4.6,"[historic, iconic, cultural, morning]",NaN,1.0
4,place_005,Pantheon,historic_site,Rome,Lazio,Pigna,Two thousand years old and still the best-preserved ancient building on earth. The oculus is gen...,41.8986,12.4769,9:00-19:00,45.0,€,4.8,"[iconic, historic, cultural, tourist-heavy]",NaN,0.0

In [3]:
# One full record, top to bottom
df.iloc[0]

id                                                                                                            place_001
name                                                                                                          Colosseum
type                                                                                                      historic_site
city                                                                                                               Rome
region                                                                                                            Lazio
neighborhood                                                                                                      Celio
description         The most iconic structure in Rome — go early morning or book the evening experience to avoid the...
latitude                                                                                                        41.8902
longitude                                                                                                       12.4922
hours                                                                                                        9:00-19:00
duration_minutes                                                                                                  120.0
price_range                                                                                                          €€
rating                                                                                                              4.8
tags                                                                        [iconic, historic, tourist-heavy, cultural]
seasonal_notes                                                    Summer queues can be brutal — pre-book online always.
booking_required                                                                                                    1.0
Name: 0, dtype: object

In [4]:
# What's missing, by column
df.isna().sum().sort_values(ascending=False)

seasonal_notes      87
hours               33
neighborhood        19
duration_minutes     9
booking_required     1
id                   0
type                 0
name                 0
latitude             0
description          0
region               0
city                 0
price_range          0
longitude            0
tags                 0
rating               0
dtype: int64

In [5]:
df['type'].value_counts()

type
historic_site    19
restaurant       19
experience       17
museum           15
viewpoint        10
cafe              7
neighborhood      6
market            6
park              3
shop              1
Name: count, dtype: int64

In [6]:
df['city'].value_counts()

city
Rome                 30
Florence             20
Milan                15
Venice               15
Bologna               9
Modena                3
Parma                 2
Siena                 1
Maranello             1
Bellagio              1
Lenno                 1
Burano                1
Como                  1
Pienza                1
Isola della Scala     1
Padua                 1
Name: count, dtype: int64

In [7]:
df['neighborhood'].unique()

<StringArray>
[                    'Celio',                'Trastevere',
                     'Pigna',                   'Parione',
                   'Parioli',                     'Borgo',
                      'Ripa',                   'Pigneto',
                  'Aventino',                 'Testaccio',
                     'Trevi',                     'Prati',
                         nan,           'Campo de' Fiori',
                  'Flaminio',                   'Colonna',
                  'Oltrarno',               'Santa Croce',
               'San Lorenzo',                 'San Marco',
              'San Giovanni',                  'Gavinana',
              'Quadrilatero',                   'Irnerio',
 'Piazza di Porta Ravegnana',        'University Quarter',
                 'Saragozza',            'Centro Storico',
               'Castiglione',                     'Duomo',
                   'Magenta',                   'Navigli',
                     'Brera',                      'Lodi',
                     'Isola',                  'San Polo',
                'Cannaregio',                 'Dorsoduro',
                  'Castello',      'San Giorgio Maggiore',
                 'Gianicolo',             'Sant'Ambrogio',
                  'Ostiense',   'Quadrilatero della Moda',
     'Piazza della Signoria']
Length: 45, dtype: str

In [8]:
df['price_range'].value_counts()

price_range
€€      46
€       42
€€€     10
€€€€     5
Name: count, dtype: int64

In [9]:
# Every distinct hours string
for h in sorted(df['hours'].dropna().unique()):
    print(h)

10:00-23:00
11:00-23:00
11:00-24:00
12:00-14:30, 19:00-22:30
12:00-23:00
7:30-24:00
8:00-01:00
8:15-13:50
8:15-16:30
8am-7pm
9:00-18:00
9:00-19:00
9:00-19:30
9:00-21:00
9:00-23:00
9:00-24:00
9:30-17:30
9:30-18:00
9am-12:30pm
Daily 10:00-24:00
Daily 9:00-23:00
Evenings
Mon-Fri 7:00-14:00, Sat 7:00-17:00
Mon-Sat 10:00-12:00, 14:30-18:00
Mon-Sat 10:00-18:00
Mon-Sat 10:00-20:00
Mon-Sat 11:00-21:00
Mon-Sat 12:00-14:30
Mon-Sat 12:30-14:30, 19:30-22:30
Mon-Sat 12:30-15:30, 19:30-23:00
Mon-Sat 19:30-22:30
Mon-Sat 7:00-14:00
Mon-Sat 8:00-13:00, 16:30-19:30
Mon-Sat 9:00-18:00
Mon-Sat 9:00-19:00
Mon-Sat 9:30-17:15, Sun 14:00-17:00
Mon-Sat 9:30-17:30, Sun 14:00-17:30
Morning only
Sat-Sun 9:00-19:00
Tues, Thurs-Sun 10:00-18:00
Tues-Sat 12:30-14:00, 20:00-22:00
Tues-Sat 12:30-14:30, 19:30-22:00
Tues-Sat 13:00-15:00, 20:00-22:30
Tues-Sun 10:00-19:30
Tues-Sun 12:00-14:30, 19:00-22:30
Tues-Sun 12:00-15:00, 19:00-23:00
Tues-Sun 12:30-14:30, 19:00-22:00
Tues-Sun 12:30-14:30, 19:30-22:30
Tues-Sun 18:00-23:00
Tues-Sun 19:30-22:30
Tues-Sun 8:15-18:50
Tues-Sun 8:15-19:00
Tues-Sun 8:30-19:15
Tues-Sun 9:00-19:00
Wed-Mon 10:00-18:00
Wed-Mon 10:00-19:00
Wed-Sun 12:30-23:30

In [10]:
# Hours that don't look like the usual 'Days HH:MM-HH:MM' shape
df[df['hours'].notna() & ~df['hours'].str.contains(':')][['name', 'type', 'hours']]

                                         name           type         hours
5                      Campo de' Fiori Market         market  Morning only
36                      Aperitivo at Rasputin           cafe      Evenings
39                       San Miniato al Monte  historic_site       8am-7pm
67            Cicchetti Bar Crawl, Cannaregio     experience      Evenings
78  Prosciutto e Melone at Cremeria Mascareta           cafe      Evenings
99              Aperitivo Culture Walk, Milan     experience      Evenings

In [11]:
# Every seasonal note
for note in df['seasonal_notes'].dropna():
    print(note)

Summer queues can be brutal — pre-book online always.
Closed Sundays except last Sunday of the month (free entry, massive crowds).
Best April-October. Road closed to cars on Sundays only.
Booking essential April-October.
Summer hours extend to 19:30. Can be brutally hot July-August.
Open April-October only. Best in September during harvest season.
Tours run weekday mornings only — plan ahead.
Tickets frequently sell out 2 months in advance.
Best May-September when canal-side seating is open.
Third weekend of each month only.
Open April-October only. Summer weekends extremely crowded.
Open April-October only.
Rooftop open May-September only.
Open April-October only.
October only — check exact festival dates before planning.
Best April-October.

In [12]:
df['tags'].explode().value_counts()

tags
cultural           44
local-favorite     43
food               39
scenic             35
historic           32
iconic             31
photogenic         26
hidden-gem         22
views              22
morning            21
art                18
tourist-heavy      17
evening            16
outdoors           14
romantic           13
rainy-day          12
wine               12
splurge            11
quiet               9
market              8
budget              6
relaxing            6
active              6
experience          6
family-friendly     5
shop                3
free                2
modern              2
lively              1
seasonal            1
local_favorite      1
Name: count, dtype: int64

In [13]:
# local_favorite vs local-favorite — the one inconsistent tag
df[df['tags'].apply(lambda tags: 'local_favorite' in tags)][['id', 'name', 'tags']]

,id,name,tags
99,place_100,"Aperitivo Culture Walk, Milan","[local_favorite, evening, food, wine, cultural, active]"

In [14]:
df['rating'].describe()

count    103.000000
mean       4.553398
std        0.333671
min        2.100000
25%        4.500000
50%        4.600000
75%        4.700000
max        5.000000
Name: rating, dtype: float64

In [15]:
df.nsmallest(5, 'rating')[['name', 'type', 'city', 'rating']]

                                   name           type      city  rating
24                  Hard Rock Cafe Rome     restaurant      Rome     2.1
11  Mouth of Truth (Bocca della Verità)  historic_site      Rome     3.8
18                        Spanish Steps  historic_site      Rome     3.9
81                 Rossopomodoro, Milan     restaurant     Milan     3.9
30                     Mercato Centrale     experience  Florence     4.0

In [16]:
df['duration_minutes'].value_counts().sort_index()

duration_minutes
15.0      1
20.0      3
30.0      3
45.0      9
60.0     10
75.0      3
90.0     27
100.0     3
120.0    13
150.0     5
180.0     6
210.0     1
240.0     3
300.0     2
360.0     4
480.0     1
Name: count, dtype: int64

In [17]:
# Floats, not bools — the single null drags the whole column to float
df['booking_required'].value_counts(dropna=False)

booking_required
0.0    71
1.0    31
NaN     1
Name: count, dtype: int64

In [18]:
# Rows with no hours — mostly neighborhoods, viewpoints, and day trips
df[df['hours'].isna()][['id', 'name', 'type', 'city', 'duration_minutes']]

,id,name,type,city,duration_minutes
1,place_002,Trastevere Neighborhood,neighborhood,Rome,180.0
7,place_008,Piazza Navona,historic_site,Rome,45.0
12,place_013,Pigneto Neighborhood,neighborhood,Rome,120.0
13,place_014,Aventine Keyhole,viewpoint,Rome,NaN
17,place_018,Trevi Fountain,historic_site,Rome,30.0
18,place_019,Spanish Steps,historic_site,Rome,20.0
20,place_021,Appian Way Bike Ride,experience,Rome,240.0
22,place_023,Piazza del Popolo at Dawn,viewpoint,Rome,NaN
26,place_027,Piazzale Michelangelo,viewpoint,Florence,NaN
27,place_028,Oltrarno Neighborhood,neighborhood,Florence,180.0
34,place_035,Chianti Day Trip by Bike,experience,Florence,480.0
37,place_038,Siena Day Trip,experience,Siena,360.0
43,place_044,"Traditional Balsamic Vinegar Tasting, Modena",experience,Modena,90.0
48,place_049,University of Bologna Porticoes Walk,experience,Bologna,120.0
51,place_052,Piazza Maggiore at Night,viewpoint,Bologna,NaN
52,place_053,"Cheese and Prosciutto Tour, Parma",experience,Parma,360.0
56,place_057,Navigli Canals at Aperitivo Hour,neighborhood,Milan,120.0
59,place_060,Galleria Vittorio Emanuele II,historic_site,Milan,45.0
62,place_063,"Bellagio, Lake Como",experience,Bellagio,360.0
65,place_066,Rialto Bridge,historic_site,Venice,NaN
69,place_070,Burano Island Trip,experience,Burano,300.0
70,place_071,Gondola on a Back Canal,experience,Venice,60.0
71,place_072,Dorsoduro Neighborhood,neighborhood,Venice,180.0
74,place_075,Early Morning in Cannaregio,experience,Venice,90.0
76,place_077,Trevi Fountain by Night,viewpoint,Rome,NaN
79,place_080,Borghese Park (Villa Borghese),park,Rome,120.0
83,place_084,Ponte Vecchio,historic_site,Florence,30.0
84,place_085,Como Town Lakefront,viewpoint,Como,NaN
88,place_089,Pienza Village Day Trip,experience,Pienza,360.0
89,place_090,Isola della Scala Risotto Festival,experience,Isola della Scala,300.0
92,place_093,"Piazza del Duomo, Florence (Exterior)",viewpoint,Florence,NaN
96,place_097,"Passeggiata del Gianicolo, Rome",viewpoint,Rome,NaN
101,place_102,"Quadrilatero della Moda, Milan",neighborhood,Milan,90.0

In [19]:
# Rows with no duration
df[df['duration_minutes'].isna()][['id', 'name', 'type', 'city', 'hours']]

,id,name,type,city,hours
13,place_014,Aventine Keyhole,viewpoint,Rome,NaN
22,place_023,Piazza del Popolo at Dawn,viewpoint,Rome,NaN
26,place_027,Piazzale Michelangelo,viewpoint,Florence,NaN
51,place_052,Piazza Maggiore at Night,viewpoint,Bologna,NaN
65,place_066,Rialto Bridge,historic_site,Venice,NaN
76,place_077,Trevi Fountain by Night,viewpoint,Rome,NaN
84,place_085,Como Town Lakefront,viewpoint,Como,NaN
92,place_093,"Piazza del Duomo, Florence (Exterior)",viewpoint,Florence,NaN
96,place_097,"Passeggiata del Gianicolo, Rome",viewpoint,Rome,NaN

In [20]:
# Same coordinates, different rows
df[df.duplicated(['latitude', 'longitude'], keep=False)].sort_values('latitude')[
    ['id', 'name', 'type', 'city', 'latitude', 'longitude']
]

,id,name,type,city,latitude,longitude
17,place_018,Trevi Fountain,historic_site,Rome,41.9009,12.4833
76,place_077,Trevi Fountain by Night,viewpoint,Rome,41.9009,12.4833
29,place_030,Mercato Centrale Firenze,market,Florence,43.7767,11.2535
30,place_031,Mercato Centrale,experience,Florence,43.7767,11.2535

In [21]:
# How many places of each type, per city
pd.crosstab(df['city'], df['type'])

type,cafe,experience,historic_site,market,museum,neighborhood,park,restaurant,shop,viewpoint
city,,,,,,,,,,
Bellagio,0,1,0,0,0,0,0,0,0,0
Bologna,1,2,1,1,1,0,0,2,0,1
Burano,0,1,0,0,0,0,0,0,0,0
Como,0,0,0,0,0,0,0,0,0,1
Florence,1,2,3,1,5,1,1,4,0,2
Isola della Scala,0,1,0,0,0,0,0,0,0,0
Lenno,0,0,1,0,0,0,0,0,0,0
Maranello,0,0,0,0,1,0,0,0,0,0
Milan,1,1,3,1,4,2,0,2,0,1
Modena,0,2,0,0,0,0,0,1,0,0
Padua,0,0,0,0,0,0,1,0,0,0
Parma,0,1,0,0,0,0,0,1,0,0
Pienza,0,1,0,0,0,0,0,0,0,0
Rome,1,1,9,3,2,2,1,6,1,4
Siena,0,1,0,0,0,0,0,0,0,0
Venice,3,3,2,0,2,1,0,3,0,1

In [22]:
# Total minutes of stuff to do per city — Rome and Florence are the only ones with 3 days in them
df.groupby('city')['duration_minutes'].agg(['count', 'sum', 'mean']).sort_values('sum', ascending=False)

                   count     sum        mean
city
Rome                  26  2360.0   90.769231
Florence              18  2230.0  123.888889
Venice                14  1365.0   97.500000
Milan                 15  1360.0   90.666667
Bologna                8   755.0   94.375000
Parma                  2   435.0  217.500000
Modena                 3   420.0  140.000000
Bellagio               1   360.0  360.000000
Siena                  1   360.0  360.000000
Pienza                 1   360.0  360.000000
Burano                 1   300.0  300.000000
Isola della Scala      1   300.0  300.000000
Maranello              1   150.0  150.000000
Lenno                  1   120.0  120.000000
Padua                  1    90.0   90.000000
Como                   0     0.0         NaN

In [23]:
# Lat/lon range per city — Milan's is suspiciously wide
df.groupby('city')[['latitude', 'longitude']].agg(['min', 'max']).round(3)

                  latitude         longitude
                       min     max       min     max
city
Bellagio            45.985  45.985     9.259   9.259
Bologna             44.489  44.499    11.328  11.351
Burano              45.485  45.485    12.418  12.418
Como                45.808  45.808     9.085   9.085
Florence            43.583  43.777    11.246  11.317
Isola della Scala   45.266  45.266    11.001  11.001
Lenno               45.961  45.961     9.163   9.163
Maranello           44.529  44.529    10.865  10.865
Milan               45.444  45.479     9.171  11.191
Modena              44.645  44.647    10.926  10.930
Padua               45.399  45.399    11.881  11.881
Parma               44.802  44.802    10.327  10.328
Pienza              43.078  43.078    11.679  11.679
Rome                41.855  41.914    12.421  12.534
Siena               43.319  43.319    11.331  11.331
Venice              45.429  45.448    12.316  12.352

In [24]:
# Brera Antique Market is in Milan but its longitude is 11.19 (should be ~9.19)
df[df['city'] == 'Milan'][['id', 'name', 'neighborhood', 'latitude', 'longitude']]

,id,name,neighborhood,latitude,longitude
54,place_055,Duomo di Milano,Duomo,45.4641,9.1919
55,place_056,The Last Supper (Cenacolo Vinciano),Magenta,45.4658,9.1713
56,place_057,Navigli Canals at Aperitivo Hour,Navigli,45.4538,9.1730
57,place_058,Pinacoteca di Brera,Brera,45.4718,9.1883
58,place_059,Brera Antique Market,Brera,45.4724,11.1910
59,place_060,Galleria Vittorio Emanuele II,Duomo,45.4660,9.1899
60,place_061,Risotto alla Milanese at Trattoria Milanese,Duomo,45.4638,9.1854
61,place_062,Fondazione Prada,Lodi,45.4443,9.2024
64,place_065,Aperitivo at Ceresio 7,Isola,45.4769,9.1782
81,place_082,"Rossopomodoro, Milan",Brera,45.4717,9.1893
85,place_086,"Museo del Novecento, Milan",Duomo,45.4640,9.1892
93,place_094,"Roof Garden at the Rinascente, Milan",Duomo,45.4654,9.1898
97,place_098,"Basilica di Sant'Ambrogio, Milan",Sant'Ambrogio,45.4603,9.1741
99,place_100,"Aperitivo Culture Walk, Milan",Isola,45.4791,9.1875
101,place_102,"Quadrilatero della Moda, Milan",Quadrilatero della Moda,45.4695,9.1991

In [25]:
# Everything in one city
df[df['city'] == 'Rome'][['name', 'type', 'neighborhood', 'hours', 'duration_minutes', 'rating']]

,name,type,neighborhood,hours,duration_minutes,rating
0,Colosseum,historic_site,Celio,9:00-19:00,120.0,4.8
1,Trastevere Neighborhood,neighborhood,Trastevere,NaN,180.0,4.7
2,Da Enzo al 29,restaurant,Trastevere,"Mon-Sat 12:30-14:30, 19:30-22:30",90.0,4.6
3,Roman Forum,historic_site,Celio,9:00-19:00,90.0,4.6
4,Pantheon,historic_site,Pigna,9:00-19:00,45.0,4.8
5,Campo de' Fiori Market,market,Parione,Morning only,60.0,4.2
6,Borghese Gallery,museum,Parioli,Tues-Sun 9:00-19:00,120.0,4.9
7,Piazza Navona,historic_site,Parione,NaN,45.0,4.5
8,Osteria Fernanda,restaurant,Trastevere,Tues-Sun 19:30-22:30,100.0,4.5
9,Vatican Museums,museum,Borgo,Mon-Sat 9:00-18:00,240.0,4.7
10,Gelato at Giolitti,cafe,Pigna,7:30-24:00,20.0,4.3
11,Mouth of Truth (Bocca della Verità),historic_site,Ripa,9:30-17:30,15.0,3.8
12,Pigneto Neighborhood,neighborhood,Pigneto,NaN,120.0,4.4
13,Aventine Keyhole,viewpoint,Aventino,NaN,NaN,4.6
14,Mercato Testaccio,market,Testaccio,Mon-Sat 7:00-14:00,60.0,4.7
15,Palatine Hill,historic_site,Celio,9:00-19:00,90.0,4.4
16,Castel Sant'Angelo,historic_site,Borgo,9:00-19:30,90.0,4.5
17,Trevi Fountain,historic_site,Trevi,NaN,30.0,4.7
18,Spanish Steps,historic_site,Trevi,NaN,20.0,3.9
19,Il Sorpasso,restaurant,Prati,8:00-01:00,90.0,4.4
20,Appian Way Bike Ride,experience,NaN,NaN,240.0,4.8
21,Roscioli Salumeria,restaurant,Campo de' Fiori,"Mon-Sat 12:30-15:30, 19:30-23:00",90.0,4.7
22,Piazza del Popolo at Dawn,viewpoint,Flaminio,NaN,NaN,4.6
23,Fontanella Borghese Book Market,market,Colonna,Mon-Sat 9:00-19:00,45.0,4.1
24,Hard Rock Cafe Rome,restaurant,Trevi,11:00-24:00,90.0,2.1
41,Trattoria da Cesare al Casaletto,restaurant,NaN,"Tues-Sat 13:00-15:00, 20:00-22:30",90.0,4.8
76,Trevi Fountain by Night,viewpoint,Trevi,NaN,NaN,4.6
79,Borghese Park (Villa Borghese),park,Parioli,NaN,120.0,4.5
96,"Passeggiata del Gianicolo, Rome",viewpoint,Gianicolo,NaN,NaN,4.6
98,Eataly Roma Ostiense,shop,Ostiense,9:00-24:00,60.0,4.1

In [26]:
# Everything with a given tag
df[df['tags'].apply(lambda tags: 'hidden-gem' in tags)][['name', 'type', 'city', 'rating']]

,name,type,city,rating
2,Da Enzo al 29,restaurant,Rome,4.6
12,Pigneto Neighborhood,neighborhood,Rome,4.4
13,Aventine Keyhole,viewpoint,Rome,4.6
22,Piazza del Popolo at Dawn,viewpoint,Rome,4.6
23,Fontanella Borghese Book Market,market,Rome,4.1
27,Oltrarno Neighborhood,neighborhood,Florence,4.7
32,Buca dell'Orafo,restaurant,Florence,4.4
36,Aperitivo at Rasputin,cafe,Florence,4.5
39,San Miniato al Monte,historic_site,Florence,4.7
41,Trattoria da Cesare al Casaletto,restaurant,Rome,4.8
43,"Traditional Balsamic Vinegar Tasting, Modena",experience,Modena,4.8
50,Pinacoteca Nazionale di Bologna,museum,Bologna,4.5
58,Brera Antique Market,market,Milan,4.2
67,"Cicchetti Bar Crawl, Cannaregio",experience,Venice,4.8
74,Early Morning in Cannaregio,experience,Venice,4.7
75,Osteria Alla Staffa,restaurant,Venice,4.5
78,Prosciutto e Melone at Cremeria Mascareta,cafe,Venice,4.7
87,San Giorgio Maggiore Campanile,viewpoint,Venice,4.8
93,"Roof Garden at the Rinascente, Milan",viewpoint,Milan,4.5
97,"Basilica di Sant'Ambrogio, Milan",historic_site,Milan,4.6
100,"Museo Nazionale del Bargello, Florence",museum,Florence,4.7
102,Palazzo Vecchio,museum,Florence,4.5

In [27]:
# Keyword search in the descriptions
df[df['description'].str.contains('rooftop|sunset', case=False)][['name', 'city', 'description']]

,name,city,description
16,Castel Sant'Angelo,Rome,"A former tomb, fortress, and prison — the rooftop terrace has arguably the best views of the Tib..."
26,Piazzale Michelangelo,Florence,The classic panoramic view of Florence — every travel photo of the Duomo and Arno is taken from ...
54,Duomo di Milano,Milan,"600 years in the making — the most elaborate Gothic cathedral in the world and, from its rooftop..."
64,Aperitivo at Ceresio 7,Milan,A rooftop pool bar on a design-district building — aperitivo at sunset with the entire Milan sky...
93,"Roof Garden at the Rinascente, Milan",Milan,Take the escalators to the top floor of the La Rinascente department store — there's a rooftop b...

In [28]:
# Read a few descriptions in full
for _, row in df.sample(5, random_state=1).iterrows():
    print(f"{row['name']} ({row['type']}, {row['city']})")
    print(row['description'])
    print()

Bellagio, Lake Como (experience, Bellagio)
The jewel of Lake Como — terraced gardens, silk shops, lake-view restaurants, and a ferry crossing that gives you one of the most beautiful panoramas in Europe. The ferry from Como takes 2 hours; the hydrofoil is 45 minutes.

Osteria dell'Enoteca (restaurant, Florence)
Florence's best serious restaurant — creative Tuscan cooking with one of the deepest wine lists in the region. Not cheap, but for a special occasion dinner in Florence, nothing competes.

San Miniato al Monte (historic_site, Florence)
Hike up past Piazzale Michelangelo to this 11th-century Romanesque church — few tourists make it this far and the views are even better. The mosaic facade glitters in afternoon sun.

Burano Island Trip (experience, Burano)
Take the vaporetto 45 minutes into the lagoon to the island of brightly painted houses — one of the most photogenic places in Italy, genuinely quiet on weekday mornings, and worth it for the seafood lunch alone.

Palazzo Vecchio (museum, Florence)
Florence's town hall for 700 years — climb the tower for the best view in the city (better than Piazzale Michelangelo) and explore the extraordinary frescoed halls inside. Often overlooked in favor of the Uffizi next door.